Fix typings
apexcharts/vue3-apexcharts pull request #22
Opened 2021-05-04 16:25 UTC by IlCallo

Closes #2
Closes #18

See #18 for context

`setLocale` types are missing as haven't found how it should work anywhere

2021-05-04 17:45 UTC, junedchhipa requested changes
Thanks for the PR.
I have added 3 comments to remove the `addText` method

2021-05-04 17:45 UTC, junedchhipa commented on typings/vue-apexcharts.d.ts
> +  addText(text: string): void;
addText method is no longer available. Please remote it.

2021-05-04 17:45 UTC, junedchhipa commented on src/vue3-apexcharts.js
> +      addText,
addText method is no longer available. Please remove it

2021-05-04 17:45 UTC, junedchhipa commented on src/vue3-apexcharts.js
>      const addText = options => {
addText method is no longer available. Please remove it

2021-05-04 18:58 UTC, IlCallo commented
Done

2021-05-04 18:59 UTC, junedchhipa approved these changes

2021-05-04 18:59 UTC, merged

2021-05-04 19:43 UTC, GTB3NW commented
TYSM for these changes. I'll give it a go and see if everything is working for me :)

2021-05-04 20:45 UTC, GTB3NW commented
@junedchhipa would it be possible to get this tagged please? Installing via commit is not working (probably me doing something wrong).

2021-05-05 17:45 UTC, junedchhipa commented
I will release a new version very soon (in the next 24-48 hours)

2021-05-05 18:07 UTC, GTB3NW commented
> I will release a new version very soon (in the next 24-48 hours)

Smashing, glad to hear it! :)